### ISSUE TITLE
HTMLElement is not defined in Angular SSR for ripple service

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1401]
In Angular SSR `ripple.service.ts` line no: 19 

`export const MATCHES = getMatchesProperty(HTMLElement.prototype);`

generates following error.

ReferenceError: HTMLElement is not defined
    at D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles
    at D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles
    at Object.<anonymous> (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@ang
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

I tried to fix it using isBrowser from platform however it is exported element and not inside class so can not use platform here.

**Comment by trimox** [comment]
Duplicated. Thanks for reporting. Lemme take a look

**Comment by trimox** [comment]
Working on a PR, should be available in a bit.

**Comment by JeetChaudhari** [comment]
Thanks @trimox , If you need any help, let me know.
