### ISSUE TITLE
Window is not defined in Angular SSR for top app bar

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1419]
In Angular SSR build failed due to following error.

ERROR ReferenceError: window is not defined
    at new a (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-top-app-bar.umd.js:339:222)
    at createClass (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9324:24)
    at createDirectiveInstance (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9205:24)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10425:40)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9)
Unhandled Promise rejection: window is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: window is not defined
    at new a (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-top-app-bar.umd.js:339:222)
    at createClass (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9324:24)
    at createDirectiveInstance (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9205:24)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10425:40)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9) ReferenceError: window is not defined
    at new a (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-top-app-bar.umd.js:339:222)
    at createClass (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9324:24)
    at createDirectiveInstance (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9205:24)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10425:40)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10741:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at createViewNodes (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10453:9)

**Comment by trimox** [comment]
Thanks for reporting, fixing this now.
