### ISSUE TITLE
checkbox: Support SSR

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1421]
On Angular SSR build failed due to following error.

Unhandled Promise rejection: Cannot redefine property: checked ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot redefine property: checked
    at Function.defineProperty (<anonymous>)
    at D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:276:458
    at Array.forEach (<anonymous>)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:276:342)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:270:2850)
    at j.ngOnDestroy (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:333:107)
    at callProviderLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9592:22)
    at callElementProvidersLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9560:17)
    at callLifecycleHooksChildrenFirst (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9550:33)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10612:9) TypeError: Cannot redefine property: check
ed
    at Function.defineProperty (<anonymous>)
    at D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:276:458
    at Array.forEach (<anonymous>)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:276:342)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:270:2850)
    at j.ngOnDestroy (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-checkbox.umd.js:333:107)
    at callProviderLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9592:22)
    at callElementProvidersLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9560:17)
    at callLifecycleHooksChildrenFirst (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9550:33)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10612:9)

**Comment by trimox** [comment]
Duplicated. Fixing this now

**Comment by trimox** [comment]
Appears to be a problem upstream. Researching a workaround..
reference: https://github.com/material-components/material-components-web/issues/3666

**Comment by trimox** [comment]
Update. SSR support for checkbox will come as soon as https://github.com/material-components/material-components-web/pull/4073 is merged upstream.
