### ISSUE TITLE
ERROR TypeError: a._getHostElement(...).getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1423]
On Angular SSR following error occurs.

ERROR TypeError: a._getHostElement(...).getBoundingClientRect is not a function
    at Object.computeBoundingRect (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-drawer.umd.js:360:369)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-drawer.umd.js:186:159)
    at a.set [as open] (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-drawer.umd.js:342:81)
    at updateProp (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9475:41)
    at checkAndUpdateDirectiveInline (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9226:23)
    at checkAndUpdateNodeInline (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10533:24)
    at checkAndUpdateNode (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10495:20)
    at prodCheckAndUpdateNode (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:11035:9)
    at Object.updateDirectives (D:\Dev\jeet-chaudhari\universal-starter\dist\server\main.js:2485:1086)
    at Object.updateDirectives (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10824:76)

**Comment by trimox** [comment]
Once I merge a PR for #1424 , this will be resolved.

reference: https://github.com/material-components/material-components-web/pull/3683

**Comment by trimox** [comment]
#1425 merged. Give that a try, let's see if drawer is working for ya now.
