### ISSUE TITLE
ERROR TypeError: Cannot read property 'valid' of undefined (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1441]
Angular SSR build shows following error

ERROR TypeError: Cannot read property 'valid' of undefined
    at r.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-textfield.umd.js:495:94)
    at r.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-textfield.umd.js:465:82)
    at r.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-textfield.umd.js:462:88)
    at Timeout.<anonymous> (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-textfield.umd.js:908:155)
    at ZoneDelegate.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:3873:37)
    at ZoneDelegate.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:496:34)
    at Timeout.ZoneTask.invoke (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:485:48)

**Comment by trimox** [comment]
Thanks for reporting this issue.

Looks to be coming from MDC's foundation code, will research for workaround.
