### ISSUE TITLE
Unhandled Promise rejection: cancelAnimationFrame is not defined (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1442]
Angular SSR build shows following error

Unhandled Promise rejection: cancelAnimationFrame is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: cancelAnimationFrame is not defi
ned
    at h.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu-surface.umd.js:147:1153)
    at a.g.destroyMenuSurface (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu-surface.umd.js:273:158)
    at a.ngOnDestroy (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu.umd.js:527:221)
    at callProviderLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9592:22)
    at callElementProvidersLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9560:17)
    at callLifecycleHooksChildrenFirst (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9550:33)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10612:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10738:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10611:9) ReferenceError: cancelAnimationFrame is no
t defined
    at h.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu-surface.umd.js:147:1153)
    at a.g.destroyMenuSurface (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu-surface.umd.js:273:158)
    at a.ngOnDestroy (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-menu.umd.js:527:221)
    at callProviderLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9592:22)
    at callElementProvidersLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9560:17)
    at callLifecycleHooksChildrenFirst (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9550:33)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10612:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10738:17)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)
    at destroyView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10611:9)

**Comment by trimox** [comment]
@JeetChaudhari This is an interesting one. I'm tackling it now.

**Comment by trimox** [comment]
@JeetChaudhari PR https://github.com/trimox/angular-mdc-web/pull/1451 will resolve this one for ya.
