### ISSUE TITLE
tab-indicator: getBoundingClientRect is not a function (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1467]
Following Error is generated in Angular SSR build

TypeError: d.content.nativeElement.getBoundingClientRect is not a function
             at Object.computeContentClientRect (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-indicator.umd.js:142:24
7)
             at a.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-indicator.umd.js:103:348)
             at d.computeContentClientRect (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-indicator.umd.js:151:48)
             at a.computeIndicatorClientRect (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab.umd.js:376:47)
             at Object.getTabIndicatorClientRectAtIndex (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-bar.umd.js:851:
918)
             at r.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-bar.umd.js:695:218)
             at t.activateTab (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-bar.umd.js:881:74)
             at D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-tab-bar.umd.js:853:199
             at ZoneDelegate.invoke (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:388:26)
             at Object.onInvoke (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:3882:37) },

**Comment by trimox** [comment]
Testing a PR for this

**Comment by trimox** [comment]
Closed in #1474
