### ISSUE TITLE
slider: getBoundingClientRect is not a function (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1468]
ERROR TypeError: b._getHostElement(...).getBoundingClientRect is not a function
    at Object.computeBoundingRect (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-slider.umd.js:303:526)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-slider.umd.js:203:1685)
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-slider.umd.js:203:662)
    at a.ngAfterViewInit (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-slider.umd.js:305:86)
    at callProviderLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9586:22)
    at callElementProvidersLifecycles (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9560:17)
    at callLifecycleHooksChildrenFirst (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9550:33)
    at checkAndUpdateView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10486:9)
    at callViewAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10718:25)
    at execComponentViewsAction (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10660:17)

**Comment by trimox** [comment]
Testing a PR
