### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of undefined (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1469]
ERROR TypeError: Cannot read property 'length' of undefined
    at n.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-select.umd.js:438:82)
    at t._propagateChanges (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-select.umd.js:579:190)
    at t.setSelectionByValue (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-select.umd.js:572:100)
    at Timeout.<anonymous> (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-select.umd.js:549:76)
    at ZoneDelegate.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:3873:37)
    at ZoneDelegate.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:496:34)
    at Timeout.ZoneTask.invoke (D:\Dev\jeet-chaudhari\universal-starter\node_modules\zone.js\dist\zone-node.js:485:48)

**Comment by JeetChaudhari** [comment]
@trimox I received an email that you could not reproduce this issue however, I can not find that comment here, did you manage to reproduce it?

**Comment by JeetChaudhari** [comment]
@trimox Now I can see your comment, weird issue! I will test it again and get back to you also if required I would set up test repo on GitHub for you to look.

**Comment by JeetChaudhari** [comment]
@trimox https://github.com/JeetChaudhari/angular-ssr-mdc
I have set up SSR repo, use yarn and add mdc build manually
You have to use yarn build:prerender to test the output.
Note: all occurances of mdc-checkbox are commented due to checkbox issue.

**Comment by trimox** [comment]
@JeetChaudhari Very nice! Checking it out now

**Comment by trimox** [comment]
@JeetChaudhari Think we got it!

![image](https://user-images.githubusercontent.com/11887843/47328186-139a5d00-d63e-11e8-960e-d79cf77051c8.png)

Before I close out any existing issue for this, do you mind pulling `master` and giving it a go? I did some quick testing here, and minus checkbox we're looking good.

**Comment by trimox** [comment]
Merging PRs. I have one more to push for tab scroller.

**Comment by JeetChaudhari** [comment]
@trimox Testing changes now. Would post results after done.

**Comment by JeetChaudhari** [comment]
@trimox I build the app using prerender but I got this strange error as follows. Not sure if it is because of some checkbox content that I commented or something else.

Error retrieving icon:
undefined
onSelectionChange: undefined undefined
undefined
onSelectionChange: undefined undefined
onSelectionChange: undefined undefined
onSelectionChange: undefined undefined
{ source:
   a {
     _changeDetectorRef:
      ViewRef_ { _view: [Object], _viewContainerRef: null, _appRef: null },
     ripple:
      b {
        _ngZone: [NgZone],
        _platform: [d],
        _elementRef: [ElementRef],
        _destroy: [Subject],
        initialized: undefined },
     elementRef: ElementRef { nativeElement: [HTMLUnknownElement] },
     _uniqueId: 'mdc-switch-2',
     id: 'mdc-switch-2',
     name: 'demoswitch',
     tabIndex: 0,
     change:
      EventEmitter {
        _isScalar: false,
        observers: [Array],
        closed: false,
        isStopped: false,
        hasError: false,
        thrownError: null,
        __isAsync: false },
     _onChange: [Function],
     _onTouched: [Function],
     _foundation: b { adapter_: [Object] },
     inputElement: ElementRef { nativeElement: [HTMLInputElement] },
     thumbUnderlay: ElementRef { nativeElement: [HTMLDivElement] },
     _checked: false },
  checked: false }
{ source:
   a {
     _changeDetectorRef:
      ViewRef_ { _view: [Object], _viewContainerRef: null, _appRef: null },
     ripple:
      b {
        _ngZone: [NgZone],
        _platform: [d],
        _elementRef: [ElementRef],
        _destroy: [Subject],
        initialized: undefined },
     elementRef: ElementRef { nativeElement: [HTMLUnknownElement] },
     _uniqueId: 'mdc-switch-2',
     id: 'mdc-switch-2',
     name: 'demoswitch',
     tabIndex: 0,
     change:
      EventEmitter {
        _isScalar: false,
        observers: [Array],
        closed: false,
        isStopped: false,
        hasError: false,
        thrownError: null,
        __isAsync: false },
     _onChange: [Function],
     _onTouched: [Function],
     _foundation: b { adapter_: [Object] },
     inputElement: ElementRef { nativeElement: [HTMLInputElement] },
     thumbUnderlay: ElementRef { nativeElement: [HTMLDivElement] },
     _checked: true },
  checked: true }
Done in 1032.57s.

**Comment by trimox** [comment]
@JeetChaudhari No worries on that odd message, it's just a console.log inside `switch-demo.ts`. I can run `yarn serve:prerender` and use the demos.

**Comment by trimox** [comment]
@JeetChaudhari Try using latest pre-release, v0.41.0-pre.1
https://github.com/trimox/angular-mdc-web/releases/tag/v0.41.0-pre.1

Lot's of improvements to `mdc-text-field` related to SSR.

**Comment by JeetChaudhari** [comment]
Hi, I would test it and let you know the results.On 28-Oct-2018 4:41 AM, Dominic Carretto <notifications@github.com> wrote:@JeetChaudhari Try using latest pre-release, v0.41.0-pre.1
https://github.com/trimox/angular-mdc-web/releases/tag/v0.41.0-pre.1
Lot's of improvements to mdc-text-field related to SSR.

**Comment by JeetChaudhari** [comment]
No issues, looking good to me.
