### ISSUE TITLE
MdcMenuSurface - Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by kctang** [trimox/angular-mdc-web#1833]
I am creating menu surface with `<mdc-menu-surface *ngIf="selected" [open]="true" hoistToBody [anchorElement]="mdcMenuSurfaceAnchor">`.

The interesting part here is that the menu surface is only rendered if `selected` is true and it will always 'open'.

The reason for this is that I have lots of menu surface in my application and rendering only when open seems to be a HUGE performance improvement.

The only problem with this performance tweak/hack seems to be:
```
xxx.html:7 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at MdcMenuSurface.push.../../node_modules/@angular-mdc/web/esm5/menu-surface.es5.js.MdcMenuSurfaceBase.destroyMenuSurface (http://localhost:4200/vendor.js:28511:48)
    at MdcMenuSurface.push.../../node_modules/@angular-mdc/web/esm5/menu-surface.es5.js.MdcMenuSurface.ngOnDestroy (http://localhost:4200/vendor.js:28673:14)
    at callProviderLifecycles (http://localhost:4200/vendor.js:142947:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.js:142915:13)
```

FWIW, I can fix the error by doing `<mdc-menu-surface [open]="selected" hoistToBody [anchorElement]="mdcMenuSurfaceAnchor">`. Everything works without the error except for the performance issue I mentioned.

Hope you can provide some guidance/fix for this.

**Comment by kctang** [comment]
After some tinkering with the problem, I got this solution:

`<mdc-menu-surface *ngIf="selected || wasSelected" [open]="selected" hoistToBody [anchorElement]="mdcMenuSurfaceAnchor">`

...where I kept the menu surface rendered as long as it has been opened before via the `wasSelected` variable (instead of relying on value of `selected`). Both `selected` and `wasSelected` is updated by the component class as app state changes.

Thanks for reading. I will close this ticket.
