### ISSUE TITLE
text-field: Cannot read property 'length' of null (Angular SSR)

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1859]
```
ERROR TypeError: Cannot read property 'length' of null
    at MDCTextFieldFoundation.init (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:234163:48)
    at MdcTextField.init (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:237011:26)
    at MdcTextField.layout (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:237221:14)
    at MdcTextField.set [as outlined] (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:236535:22)
    at updateProp (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:26304:37)
    at checkAndUpdateDirectiveInline (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:26059:19)
    at checkAndUpdateNodeInline (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:27362:20)
    at checkAndUpdateNode (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:27324:16)
    at prodCheckAndUpdateNode (/Users/me/Documents/GitHub/the-orange-alliance-ssr/dist/server.js:27865:5)
    at Object.View_TheOrangeAllianceComponent_0._angular_core__WEBPACK_IMPORTED_MODULE_1__.ɵvid._co [as updateDirectives]
```

**Comment by trimox** [comment]
@ofekashery Thanks for reporting this. Fixed as part of #1860

Closing. Will be released in v1.x.

**Comment by ofekashery** [comment]
When will this be released?
In fact, we want to deploy to production but we're waiting for the update 😁

**Comment by trimox** [comment]
@ofekashery Tonight! 👍

**Comment by trimox** [comment]
@ofekashery It's published. If you encounter ANY issues with SSR, let me know asap. I don't mind.

**Comment by trimox** [comment]
You'll want 1.0.2, publishing it in a few minutes. Tested against SSR project.

**Comment by trimox** [comment]
All set. Grab v1.0.2.
Closing.

**Comment by ofekashery** [comment]
Big Thanks!!
