### ISSUE TITLE
Fix Angular SSR compatibility

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1932]

**Comment by trimox** [comment]
```
universal-starter\node_modules\@material\dom\ponyfill.js:27
export function closest(element, selector)
SyntaxError: Unexpected token export
```

**Comment by trimox** [comment]
All set. Working great now. PR(s) incomings

**Comment by maddy2894** [comment]
I am still getting this error :(

**Comment by maddy2894** [comment]
I am still getting this error :( .. with Angular 8 and angular universal

**Comment by TryHardDood** [comment]
> I am still getting this error :( .. with Angular 8 and angular universal.
> 
> ```
> export function closest(element, selector) {
> ^^^^^^
> 
> SyntaxError: Unexpected token 'export'
> ```
> 
> "@angular-mdc/web": "^3.2.0",

Hello.
Could you share the full error log?

**Comment by maddy2894** [comment]
@TryHardDood 
```
/Users/madhavansundararaj/Documents/GitHub/entiya/node_modules/@material/dom/ponyfill.js:27
export function closest(element, selector) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/madhavansundararaj/Documents/GitHub/entiya/node_modules/@angular-mdc/web/bundles/web-ripple.umd.js:9:177
    at Object.<anonymous> (/Users/madhavansundararaj/Documents/GitHub/entiya/node_modules/@angular-mdc/web/bundles/web-ripple.umd.js:12:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/madhavansundararaj/Documents/GitHub/entiya/node_modules/@angular-mdc/web/bundles/web-list.umd.js:9:318
    at Object.<anonymous> (/Users/madhavansundararaj/Documents/GitHub/entiya/node_modules/@angular-mdc/web/bundles/web-list.umd.js:12:2)
```

**Comment by TryHardDood** [comment]
It's an error with https://www.npmjs.com/package/@material/dom which is being used in this angular-mdc-web library. I don't really know if this can be fixed from this side. (But if we can fix it, we need to do a lot of reflactoring).

Please open a new issue, with the correct title and with the error log. Thanks

**Comment by maddy2894** [comment]
@TryHardDood  Opened a new issue, https://github.com/trimox/angular-mdc-web/issues/2031#issue-540085103 

Cheers
